version: '2.3'
services:

  redis:
    image: redis:6.0-buster
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    entrypoint: redis-server
    command: --port 6379 --save "" --appendonly no

  syncer:
    image: sentinelhub/rate-limiting-guard
    container_name: syncer
    build:
      context: ./
      dockerfile: syncer/Dockerfile
    depends_on:
      redis:
        condition: service_healthy
    environment:
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
      REFRESH_BUCKETS_SEC: "${REFRESH_BUCKETS_SEC}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
